import "./globals.css";
import { Inter } from "next/font/google";
import GlobalSate from "@/context";
import Footer from "@/components/Footer/Footer";
import Navbar from "@/components/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <GlobalSate>
                    <Navbar />
                    <main className="min-h-screen mt-[86px] md:container md:mx-auto mx-4 sm:mx-8 xl:w-3/4">
                        {children}
                    </main>
                    <Footer />
                </GlobalSate>
            </body>
        </html>
    );
}
