import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import GlobalSate from "@/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <GlobalSate>
                    <Navbar />
                    <main className="flex max-h-screen flex-col mt-[82px]">
                        {children}
                    </main>
                </GlobalSate>
            </body>
        </html>
    );
}
